version: 2

models:
  - name: dim_dates
    description: Dates dimension
    columns:
      - name: id
        description: (Surrogate) primary key for this table
        constraints:
          - type: not_null
          - type: unique
      - name: date_week
        description: Date truncated to the first day of the week for this day
      - name: date_month
        description: Date truncated to the first day of the month for this day
      - name: date_year
        description: Date truncated to the first day of the year for this day

  - name: dim_postcodes
    description: PostCodes dimension table.
    columns:
      - name: country
        description: Country
      - name: state
        description: State, if applicable
      - name: city
        description: City
      - name: postal_code
        description: Postal Code
