version: 2

models:

  - name: staging_amazon_sale_report
    description: Staging table for Amazon Sales Report data
    columns:
      - name: id
        description: |
          (Surrogate) primary key for this table.
          Based on the file's "index" column to ensure file integrity.
        tests:
          - unique
          - not_null
      - name: line_item_code
      - name: order_code
      - name: date
      - name: status
      - name: fulfillment
      - name: sales_channel
      - name: ship_service_level
      - name: style
      - name: sku
      - name: category
      - name: size
      - name: asin
      - name: courier_status
      - name: quantity
      - name: currency
      - name: amount
      - name: ship_city
      - name: ship_state
      - name: ship_postal_code
      - name: ship_country
      - name: promotion_ids
      - name: b2b
      - name: fulfilled_by
      - name: unnamed_22
